# Vetores, Matrizes e Arrays

In [1]:
import numpy as np

## 1.1 Criando Vetores

In [2]:
vetor_linha = np.array([1, 2, 3])
vetor_linha

array([1, 2, 3])

In [3]:
vetor_coluna = np.array([[1],
                         [2],
                         [3]])
vetor_coluna

array([[1],
       [2],
       [3]])

## 1.2 Criando Matrizes

In [4]:
matriz = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matriz

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Matriz Esparsa

A matriz esparsa contém muitos zeros

In [6]:
from scipy import sparse

matriz = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

matriz_esparsa = sparse.csr_matrix(matriz)

matriz_esparsa

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

In [7]:
print(matriz_esparsa)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


## 1.4 Seleção de Elementos

In [8]:
vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [9]:
vector[2]

np.int64(3)

In [10]:
matrix[1, 1]

np.int64(5)

In [11]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [12]:
vector[:3]

array([1, 2, 3])

In [13]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

## 1.5 Descrevendo Matriz

In [14]:
matrix.shape

(3, 3)

In [15]:
matrix.size

9

In [16]:
matrix.ndim

2

## 1.6 Operações

In [17]:
add_100 = lambda i: i + 100

vectorized = np.vectorize(add_100)
vectorized(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [18]:
np.max(matrix)

np.int64(9)

In [19]:
np.min(matrix)

np.int64(1)

In [20]:
np.mean(matrix)

np.float64(5.0)

In [21]:
np.var(matrix)

np.float64(6.666666666666667)

In [22]:
np.std(matrix)

np.float64(2.581988897471611)

In [24]:
matrix.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
np.linalg.matrix_rank(matrix)

np.int64(2)

In [27]:
np.linalg.det(matrix)

np.float64(-9.51619735392994e-16)

In [28]:
matrix.diagonal()

array([1, 5, 9])

In [29]:
matrix.trace() # soma das diagonais

np.int64(15)

In [32]:
np.linalg.inv(matrix) # inversa da matriz

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

## 1.7 Produto Interno

In [30]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a, vector_b)

np.int64(32)

In [31]:
vector_a @ vector_b

np.int64(32)

## 1.8 Valores Aleatórios

In [33]:
np.random.seed(0)

# gera 3 floats entre 0.0 e 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [34]:
# gera inteiros entre 0 e 11 de 3 em 3
np.random.randint(0, 11, 3)

array([3, 7, 9], dtype=int32)

In [35]:
# distribuicao normal com media 0 e std 
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [36]:
np.random.uniform(1.0, 2.0, 3)

array([1.27265629, 1.47766512, 1.81216873])